"""empty message

Revision ID: 4e7d76fc9143
Revises: 
Create Date: 2023-08-30 15:10:15.998580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7d76fc9143'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_addresses',
    sa.Column('id_address', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_address')
    )
    op.create_table('tbl_authors',
    sa.Column('id_author', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_author')
    )
    op.create_table('tbl_bookshelves',
    sa.Column('id_bookshelf', sa.UUID(), nullable=False),
    sa.Column('bookshelf', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_bookshelf')
    )
    op.create_table('tbl_categories',
    sa.Column('id_category', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_category')
    )
    op.create_table('tbl_publishers',
    sa.Column('id_publisher', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_publisher')
    )
    op.create_table('tbl_roles',
    sa.Column('id_role', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('tbl_books',
    sa.Column('id_book', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('id_author', sa.UUID(), nullable=True),
    sa.Column('id_publisher', sa.UUID(), nullable=True),
    sa.Column('id_category', sa.UUID(), nullable=True),
    sa.Column('id_bookshelf', sa.UUID(), nullable=True),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['tbl_authors.id_author'], ),
    sa.ForeignKeyConstraint(['id_bookshelf'], ['tbl_bookshelves.id_bookshelf'], ),
    sa.ForeignKeyConstraint(['id_category'], ['tbl_categories.id_category'], ),
    sa.ForeignKeyConstraint(['id_publisher'], ['tbl_publishers.id_publisher'], ),
    sa.PrimaryKeyConstraint('id_book')
    )
    op.create_table('tbl_users',
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('id_role', sa.UUID(), nullable=True),
    sa.Column('id_address', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_address'], ['tbl_addresses.id_address'], ),
    sa.ForeignKeyConstraint(['id_role'], ['tbl_roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('tbl_borrows',
    sa.Column('id_borrow', sa.UUID(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('id_user', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['tbl_users.id_user'], ),
    sa.PrimaryKeyConstraint('id_borrow')
    )
    op.create_table('tbl_carts',
    sa.Column('id_cart', sa.UUID(), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=True),
    sa.Column('id_book', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['tbl_books.id_book'], ),
    sa.ForeignKeyConstraint(['id_user'], ['tbl_users.id_user'], ),
    sa.PrimaryKeyConstraint('id_cart')
    )
    op.create_table('tbl_borrow_details',
    sa.Column('id_borrow_detail', sa.UUID(), nullable=False),
    sa.Column('id_borrow', sa.UUID(), nullable=True),
    sa.Column('id_book', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['tbl_books.id_book'], ),
    sa.ForeignKeyConstraint(['id_borrow'], ['tbl_borrows.id_borrow'], ),
    sa.PrimaryKeyConstraint('id_borrow_detail')
    )
    op.create_table('tbl_returns',
    sa.Column('id_return', sa.UUID(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.UUID(), nullable=True),
    sa.Column('id_borrow', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_borrow'], ['tbl_borrows.id_borrow'], ),
    sa.ForeignKeyConstraint(['id_user'], ['tbl_users.id_user'], ),
    sa.PrimaryKeyConstraint('id_return')
    )
    op.create_table('tbl_return_details',
    sa.Column('id_return_detail', sa.UUID(), nullable=False),
    sa.Column('id_return', sa.UUID(), nullable=True),
    sa.Column('id_book', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['tbl_books.id_book'], ),
    sa.ForeignKeyConstraint(['id_return'], ['tbl_returns.id_return'], ),
    sa.PrimaryKeyConstraint('id_return_detail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_return_details')
    op.drop_table('tbl_returns')
    op.drop_table('tbl_borrow_details')
    op.drop_table('tbl_carts')
    op.drop_table('tbl_borrows')
    op.drop_table('tbl_users')
    op.drop_table('tbl_books')
    op.drop_table('tbl_roles')
    op.drop_table('tbl_publishers')
    op.drop_table('tbl_categories')
    op.drop_table('tbl_bookshelves')
    op.drop_table('tbl_authors')
    op.drop_table('tbl_addresses')
    # ### end Alembic commands ###
